- name: Home Lab Setup
  hosts: cafeteria
  gather_facts: true
  pre_tasks:
    - name: Initialize playbook
      ansible.builtin.debug:
        msg: "Starting Home Lab Setup in {{ inventory_hostname }}"

    - name: Get OS Information
      ansible.builtin.command:
        cmd: lsb_release -a
      register: os_info
      changed_when: false

    - name: Print OS Information
      ansible.builtin.debug:
        var: os_info.stdout_lines

    - name: Install Core Deps
      become: true
      ansible.builtin.package:
        name:
          - build-essential
        update_cache: true

  roles:
    - { role: bond, when: bond_enabled | default(false) | bool }

    # Expose Local Network to Internet
    - { role: zerotier, when: zerotier_enabled | default(false) | bool }

    # Secret manager
    - { role: vault, when: vault.enabled | default(false) | bool }

    # Database
    - { role: postgres, when: postgres.enabled | default(false) | bool }

    # Apps Cluster
    - { role: k8s, when: k8s_enabled | default(false) | bool }
