- name: Download and save GPG key for Kubernetes
  become: true
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    mode: '0644'

- name: Add Kubernetes APT repository (stable)
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/ /"
    filename: kubernetes
    update_cache: true

- name: Install K8s Dependencies
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg

- name: Install K8s packages
  become: true
  ansible.builtin.apt:
    name: "{{ k8s.packages }}"
