- name: Setup Applications
  block:
    - name: Install Remote Core Apps
      kubernetes.core.k8s:
        src: "{{ item }}"
      with_items:
        - https://raw.githubusercontent.com/drone/charts/master/charts/drone/templates/deployment.yaml
        - https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml

    - name: Apply Local Deployments
      kubernetes.core.k8s:
        src: "{{ item }}"
      with_fileglob:
        - "../deployments/*.yaml"
