- name: Create Local Kube Config
  block:
    - name: Write .kube directory
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.kube"
        state: directory
        mode: '0700'

    - name: Remove old kube config
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.kube/{{ ansible_hostname }}-config"
        state: absent

    - name: Fetch kubeconfig from control plane for {{ ansible_hostname }}
      become: true
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ lookup('env', 'HOME') }}/.kube/{{ ansible_hostname }}-config"
        flat: true
        validate_checksum: false

- name: Create Remote Kube Config
  block:
    - name: Write .kube directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0700'

    - name: Create ~/.kube/config
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
