- name: Create Local Kube Config
  block:
    - name: Write .kube directory
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.kube"
        state: directory
        mode: '0700'

    - name: Fetch kubeconfig from control plane
      become: true
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "/tmp/admin.conf"
        flat: true

    - name: Install kubeconfig locally
      delegate_to: localhost
      ansible.builtin.copy:
        src: "/tmp/admin.conf"
        dest: "~/.kube/config"
        mode: '0600'

- name: Create Remote Kube Config
  block:
    - name: Write .kube directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0700'

    - name: Create ~/.kube/config
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
