---
- name: Prepare Swap Configuration
  ansible.builtin.include_tasks:
    file: swap.yml

- name: Install K8s Packages
  ansible.builtin.include_tasks:
    file: install.yml

- name: Configure K8s
  ansible.builtin.include_tasks:
    file: init.yml

- name: Setup KubeConfig
  ansible.builtin.include_tasks:
    file: kubeconfig.yml

- name: Deploy Applications
  when: false
  ansible.builtin.include_tasks:
    file: deploy.yml
