- name: Remove swap in fstab
  become: true
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*swap.*)$'
    replace: '# \1'

- name: Disable swap
  become: true
  ansible.builtin.command:
    cmd: swapoff -a
  changed_when: ansible_swaptotal_mb > 0
  when: ansible_swaptotal_mb > 0
