---
- name: Load required modules
  become: true
  community.general.modprobe:
    name: "{{ item }}"
  loop: "{{ k8s_mprobe_modules }}"

- name: Write Modules
  become: true
  ansible.builtin.template:
    src: mprobe.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Set sysctl parameters for Kubernetes networking
  register: sysctl_conf
  become: true
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl settings
  become: true
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: sysctl_conf.changed
