- name: Unload kernel modules
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  loop: "{{ k8s_mprobe_modules }}"

- name: Disable Services
  failed_when: false
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon_reload: true
  loop: "{{ k8s_services }}"

- name: Uninstall Packages
  become: true
  ansible.builtin.package:
    name:
      - kubeadm
      - kubectl
      - containernetworking-plugins
      - containerd
    state: absent
  args:
    allow_change_held_packages: true

- name: Remove K8s configuration archives
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/cni/net.d
    - /var/lib/cni/
    - /var/lib/etcd
    - /etc/kubernetes
    - /home/{{ ansible_user }}/.kube
    - /etc/crictl.yaml
    - /etc/sysctl.d/k8s.conf
    - /etc/modules-load.d/k8s.conf
    - /usr/share/keyrings/kubernetes-apt-keyring.gpg
    - /etc/apt/keyrings/kubernetes-release.key
    - /etc/sysctl.d/99-flannel.conf
    - /etc/apt/sources.list.d/kubernetes.list

- name: Uninstall Kubernetes Python client
  become: true
  ansible.builtin.pip:
    name: kubernetes
    state: absent
    break_system_packages: true
    executable: pip3
