- name: Install
  ansible.builtin.include_tasks:
    file: install.yml

- name: Ensure ZeroTier is joined to the network
  become: true
  ansible.builtin.command:
    cmd: "/usr/sbin/zerotier-cli join {{ zerotier.networkId }}"
  when: zerotier.networkId is defined
  changed_when: zerotier.networkId is defined and zerotier.networkId != ''
