- name: Install UFW
  become: true
  ansible.builtin.package:
    name: ufw
    state: present

- name: Open Ports
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ merge(network.ports, ufw_default_ports) }}"

- name: Enable UFW
  become: true
  community.general.ufw:
    state: enabled
