- name: Install Networking Deps
  become: true
  ansible.builtin.apt:
    name:
      - netplan.io
    update_cache: true

- name: Write Bonding Netplan Configuration
  become: true
  ansible.builtin.template:
    src: templates/bonding_netplan.j2
    dest: /etc/netplan/90-bonding.yaml
    owner: root
    group: root
    mode: '0600'

- name: Apply Netplan Configuration
  become: true
  ansible.builtin.command:
    cmd: netplan apply
  changed_when: false

- name: Get bonding info
  ansible.builtin.command:
    cmd: cat /proc/net/bonding/bond0
  changed_when: false
  register: bond_info

- name: Show bonding info
  ansible.builtin.debug:
    msg: "{{ bond_info.stdout_lines }}"
