- name: Install Networking Deps
  become: true
  ansible.builtin.package:
    name:
      - netplan.io

- name: Write Bonding Netplan Configuration
  become: true
  register: bond_config
  ansible.builtin.template:
    src: templates/bonding_netplan.j2
    dest: /etc/netplan/90-bonding.yaml
    owner: root
    group: root
    mode: '0600'

- name: Apply Netplan Configuration
  become: true
  ansible.builtin.command:
    cmd: netplan apply
  changed_when: bond_config.changed
