---
- name: NetPlan Setup
  become: true
  when: not netplan_uninstall
  block:
    - name: Install Networking Deps
      ansible.builtin.package:
        name:
          - netplan.io

    - name: Write Bonding Netplan Configuration
      register: bond_config
      ansible.builtin.template:
        src: templates/bonding_netplan.j2
        dest: /etc/netplan/90-bonding.yaml
        owner: root
        group: root
        mode: '0600'

    - name: Apply Netplan Configuration
      ansible.builtin.command:
        cmd: netplan apply
      changed_when: bond_config.changed

- name: Uninstall Netplan
  when: netplan_uninstall
  ansible.builtin.include_tasks:
    file: uninstall.yml
