# Bluetooth
bluetooth_enabled: true

# Kubernetes
k8s_enabled: true

# Graphics
graphics: intel

# NFS
nfs_enabled: true
nfs_server_enabled: true
nfs_client_enabled: true

nfs_exports:
  - path: /media/multimedia2

nfs_mounts:
  - path: /mnt/lidarr
    server: 192.168.1.13

  - path: /mnt/music
    server: 192.168.1.13

  - path: /media/downloads
    server: 192.168.1.10

  - path: /media/multimedia
    server: 192.168.1.10
