# Bluetooth
bluetooth_enabled: false

# Kubernetes
k8s_enabled: true

# Graphics
graphics: intel

# NFS
nfs_enabled: true
nfs_server_enabled: true
nfs_client_enabled: true

nfs_exports:
  - path: /mnt/music

nfs_mounts:
  - path: /media/downloads
    server: 192.168.1.10
    options: "rw,_netdev,nofail,x-systemd.automount"

  - path: /media/multimedia
    server: 192.168.1.10
    options: "rw,_netdev,nofail,x-systemd.automount"