# Bluetooth
bluetooth_enabled: true

# Kubernetes
k8s_enabled: true

# Graphics
graphics: intel

# NFS
nfs_enabled: true
nfs_server_enabled: true
nfs_client_enabled: true

nfs_exports:
  - path: /mnt/music
  - path: /mnt/lidarr

nfs_mounts: 
  - path: /mnt/downloads
    server: 192.168.1.12

  - path: /mnt/backups
    server: 192.168.1.12
    options: "rw,_netdev,nofail,x-systemd.automount"
