- name: Setup PostgreSQL
  when: not postgres_uninstall
  ansible.builtin.include_tasks:
    file: install.yml

- name: Configure PostgreSQL Server
  when: not postgres_uninstall
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Configure PostgreSQL Server
  when: postgres_uninstall
  ansible.builtin.include_tasks:
    file: configure.yml
